#
#Sun Apr 05 03:38:08 UTC 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --headless\=chrome, --no-sandbox, --headless\=new, --disable-gpu, --disable-dev-shm-usage, \\\\\\n                     --disable-extensions, --disable-infobars, --disable-popup-blocking, \\\\\\n                     --disable-default-apps, --ignore-certificate-errors, \\\\\\n                     --test-type, --window-size\=1920,1080, --headless], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
